include:
  - external/docker/docker-compose.yaml

services:
  game-service:
    build:
      context: .
      dockerfile: services/game-service/docker/Dockerfile
    depends_on:
      - dragncards-backend
    ports:
      - "8000:8000"
    environment:
      DRAGNCARDS_HTTP_URL: http://dragncards-backend:4000
      DRAGNCARDS_WS_URL: ws://dragncards-backend:4000/socket
      BOT_EMAIL: dev_user@example.com
      BOT_PASSWORD: password
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: "8000"
