CREATE TABLE agent_sessions (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    metadata_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    terminated_at TIMESTAMP
);

CREATE TABLE session_model_configs (
    session_id VARCHAR(36) PRIMARY KEY REFERENCES agent_sessions(id) ON DELETE CASCADE,
    provider_id VARCHAR(64) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    gateway_options JSON NOT NULL,
    provider_options JSON NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE session_skill_assignments (
    id VARCHAR(36) PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    skill_name VARCHAR(255) NOT NULL,
    skill_path TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_session_skill UNIQUE (session_id, skill_name)
);

CREATE TABLE session_mcp_assignments (
    id VARCHAR(36) PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    transport VARCHAR(64) NOT NULL,
    server_url TEXT NOT NULL,
    headers_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_session_mcp UNIQUE (session_id, name)
);

CREATE TABLE prompt_runs (
    id VARCHAR(36) PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    metadata_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE jobs (
    id VARCHAR(36) PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    prompt_run_id VARCHAR(36) NOT NULL UNIQUE REFERENCES prompt_runs(id) ON DELETE CASCADE,
    job_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INTEGER NOT NULL,
    max_attempts INTEGER NOT NULL,
    error_code VARCHAR(64),
    error_message TEXT,
    result_text TEXT,
    cancellation_requested_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE job_attempts (
    id VARCHAR(36) PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    attempt_number INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_message TEXT,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP
);

CREATE TABLE job_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    session_id VARCHAR(36) NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    event_type VARCHAR(64) NOT NULL,
    payload_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX ix_job_events_job_id ON job_events(job_id);
CREATE INDEX ix_job_events_session_id ON job_events(session_id);

CREATE TABLE job_outputs (
    id VARCHAR(36) PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    output_type VARCHAR(64) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX ix_job_outputs_job_id ON job_outputs(job_id);
